let siteData=null;const fallbackImg="images/banner.png";
async function loadData(){try{const res=await fetch("data.json",{cache:"no-store"});siteData=await res.json()}catch(e){console.error(e);siteData={site:{},posts:[],store:[],about:{}}}renderSite();bindTabs()}
function safe(v,f=""){return v||f}
function setImage(id,src){const el=document.getElementById(id);if(el&&src)el.src=src}
function renderSite(){const s=siteData.site||{};document.title=safe(s.title,"AltWorld Comics");document.getElementById("siteTitle").textContent=safe(s.title,"ALTWORLD COMICS");document.getElementById("siteTagline").textContent=safe(s.tagline,"Old tales. New adventures.");document.getElementById("siteIntro").textContent=safe(s.intro,"");setImage("siteLogo",safe(s.logo,"images/logo.png"));setImage("heroBanner",safe(s.banner,"images/banner.png"));renderPosts(siteData.posts||[]);renderStore(siteData.store||[]);renderAbout(siteData.about||{})}
function renderPosts(posts){document.getElementById("postsGrid").innerHTML=posts.map(p=>`<article class="card"><img class="card-img" src="${safe(p.image,fallbackImg)}" alt="${safe(p.title,"AltWorld Comics post")}" onerror="this.src='${fallbackImg}'"><div class="card-body"><div class="card-date">${safe(p.date,"")}</div><h3>${safe(p.title,"")}</h3><p>${safe(p.excerpt,"")}</p>${p.link?`<a class="btn" href="${p.link}" target="${p.link.startsWith("#")?"_self":"_blank"}" rel="noopener">${safe(p.linkText,"Read More")}</a>`:""}</div></article>`).join("")}
function renderStore(items){document.getElementById("storeGrid").innerHTML=items.map(i=>`<article class="card"><img class="card-img" src="${safe(i.image,fallbackImg)}" alt="${safe(i.title,"AltWorld Comics release")}" onerror="this.src='${fallbackImg}'"><div class="card-body"><div class="card-status">${safe(i.status,"")}</div><h3>${safe(i.title,"")}</h3><p>${safe(i.description,"")}</p>${i.link&&i.link!=="#"?`<a class="btn" href="${i.link}" target="_blank" rel="noopener">${safe(i.button,"Open")}</a>`:`<span class="btn">${safe(i.button,"Coming Soon")}</span>`}</div></article>`).join("")}
function renderAbout(a){document.getElementById("aboutHeading").textContent=safe(a.heading,"About AltWorld Comics");document.getElementById("aboutBody").textContent=safe(a.body,"");document.getElementById("aboutContact").textContent=safe(a.contact,"");document.getElementById("aboutX").href=safe(a.x,"#");document.getElementById("aboutInstagram").href=safe(a.instagram,"#")}
function bindTabs(){document.querySelectorAll("[data-tab]").forEach(b=>{b.addEventListener("click",e=>{e.preventDefault();showTab(b.dataset.tab)})});if(location.hash){const t=location.hash.replace("#","");if(document.getElementById(t))showTab(t)}}
function showTab(t){document.querySelectorAll(".page-section").forEach(s=>s.classList.remove("active-section"));document.querySelectorAll(".nav-link").forEach(l=>l.classList.remove("active"));document.getElementById(t)?.classList.add("active-section");document.querySelector(`.nav-link[data-tab="${t}"]`)?.classList.add("active");history.replaceState(null,"",`#${t}`);window.scrollTo({top:0,behavior:"smooth"})}
loadData();
